# Generated by Django 3.2.3 on 2021-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='nroChip',
            field=models.CharField(default=121212, max_length=20, verbose_name='Nro Chip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id_mascota',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id mascota'),
        ),
    ]
