# Generated by Django 3.2.3 on 2021-06-27 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210626_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroMascota',
            fields=[
                ('idGenero', models.AutoField(primary_key=True, serialize=False, verbose_name='Id genero')),
                ('genero', models.CharField(max_length=30, verbose_name='Género')),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idTipo_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_mascota', verbose_name='Tipo mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='genero',
            field=models.ForeignKey(default=2323, on_delete=django.db.models.deletion.CASCADE, to='core.generomascota', verbose_name='Género'),
            preserve_default=False,
        ),
    ]
