# Generated by Django 3.2.3 on 2021-06-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210626_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(max_length=2, verbose_name='esterilizado'),
        ),
    ]
